CREATE TABLE IF NOT EXISTS sites (
  id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  site_id BIGINT NOT NULL,
  path VARCHAR (255) NOT NULL,
  country VARCHAR (255) NOT NULL,
  area_or_factory VARCHAR (255) NOT NULL,
  roast INT NOT NULL,
  taste TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL
);
